ability_refresh: 60
api_key_blue: BLUEADMIN123
api_key_red: ADMIN123

host: 0.0.0.0
port: 8888

crypt_salt: "salt"
encryption_key: "ADMIN123"

exfil_dir: /tmp/caldera
reports_dir: /tmp

auth:
  local: true

requirements: {}

app.contact.dns.domain: mycaldera.caldera
app.contact.dns.socket: 0.0.0.0:8853
app.contact.gist: "none"
app.contact.html: /weather
app.contact.http: http://0.0.0.0:8888
app.contact.tcp: 0.0.0.0:7010
app.contact.udp: 0.0.0.0:7011
app.contact.websocket: 0.0.0.0:7012

app.contact.slack.api_key: ""
app.contact.slack.channel: ""

app.contact.tunnel.ssh.socket: 0.0.0.0:8022
app.contact.tunnel.ssh.user_name: sandcat
app.contact.tunnel.ssh.user_password: s4ndc4t!
app.contact.tunnel.ssh.host_key_file: "host_key"
app.contact.tunnel.ssh.host_key_passphrase: "password"

plugins:
  - atomic
  - stockpile
  - sandcat
  - gui
  - manx

users:
  blue:
    admin: admin
  red:
    admin: admin
