- name: Load Linux network config
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Load Windows network config
  include_tasks: windows.yml
  when: ansible_os_family == "Windows"
