- name: Create CALDERA directories
  file:
    path: "{{ item }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'
  loop:
    - /opt/caldera
    - /opt/caldera/conf
    - /opt/caldera/adversaries
    - /opt/caldera/data
    - /opt/caldera/operations

- name: Copy CALDERA config
  copy:
    src: local.yml
    dest: /opt/caldera/conf/local.yml
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Upload adversary profiles (APT29)
  copy:
    src: adversaries/apt29_wineloader.yml
    dest: /opt/caldera/adversaries/apt29_wineloader.yml
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Run CALDERA container
  community.docker.docker_container:
    name: caldera
    image: ghcr.io/mitre/caldera:5.2.0
    state: started
    restart_policy: unless-stopped
    recreate: true
    memory: 4g
    published_ports:
      - "8888:8888"
      - "7010:7010"
      - "7011:7011/udp"
      - "7012:7012"
      - "8022:8022"
    volumes:
      - /opt/caldera/conf/local.yml:/usr/src/app/conf/local.yml
      - /opt/caldera/adversaries:/usr/src/app/plugins/stockpile/data/adversaries
      - /opt/caldera/data:/usr/src/app/data
