- name: Create CALDERA directories
  file:
    path: "{{ item }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'
  loop:
    - /opt/caldera
    - /opt/caldera/conf
    - /opt/caldera/image 

- name: Copy Dockerfile for CALDERA
  copy:
    src: Dockerfile
    dest: /opt/caldera/image/Dockerfile
    mode: '0644'

- name: Copy CALDERA config
  copy:
    src: default.yml
    dest: /opt/caldera/conf/default.yml
    owner: vagrant
    group: vagrant
    mode: '0666'

- name: Build CALDERA image with updated Go
  community.docker.docker_image:
    name: caldera-fixed
    source: build
    build:
      path: /opt/caldera/image
    force_source: true

- name: Run CALDERA container
  community.docker.docker_container:
    name: caldera
    image: caldera-fixed
    state: started
    restart_policy: unless-stopped
    recreate: true
    memory: 4g
    published_ports:
      - "8888:8888"
      - "7010:7010"
      - "7011:7011/udp"
      - "7012:7012"
      - "8022:8022"
    volumes:
      - /opt/caldera/conf/default.yml:/usr/src/app/conf/default.yml
    command: --insecure