elastic_user: "elastic"
elastic_password: "SuperStrongElasticPassw0rd!"
kibana_system_password: "KibanaSysPassw0rd!"
sigma_user: "sigma"
sigma_password: "SuperStrongElasticPassw0rd!"
kibana_url: "http://10.10.10.30:5601"
elasticsearch_url: "http://10.10.10.30:9200"
sigma_cli_path: "/opt/sigma-pipeline/.venv/bin/sigma"

encrypted_saved_objects_key: "this_is_a_very_strong_and_long_encryption_key_32_chars_min"
encryption_key: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

caldera_group: linux_siem
