- name: Install Filebeat
  apt:
    #deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.11.1-amd64.deb
    deb: https://mirrors.aliyun.com/elasticstack/8.x/apt/pool/main/f/filebeat/filebeat-8.11.1-amd64.deb

- name: Copy Filebeat config
  copy:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0644'

- name: Enable and start Filebeat
  systemd:
    name: filebeat
    enabled: yes
    state: started
