name: "apt29-wineloader-ws"
adversary:
  adversary_id: "wineloader-apt29-custom"
planner:
  id: "788107d5-dc1e-4204-9269-38df0186d3e7"  
source:
  id: "1229254a-d40d-4929-91d0-7a0914f6b03f"  
obfuscator: "base64"
state: "running"
auto_close: true
group: "windows_ws"
jitter: "0/0"
visibility: 51
objective: "Emulate APT29 WineLoader infection chain against Windows workstations"