name: "apt29-wineloader-ws-3-step"
adversary:
  adversary_id: "apt29-wineloader"
planner:
  id: "788107d5-dc1e-4204-9269-38df0186d3e7"
source:
  id: "1229254a-d40d-4929-91d0-7a0914f6b03f"
group: "windows_ws"
objective: "Emulate APT29 WineLoader infection chain against Windows workstations"
auto_close: true
visibility: 51
