title: Linux User Creation
id: 5693457e-07c8-4723-936b-f4277726485a
status: stable
description: Detects the creation of a new local user account using useradd.
author: Eric Philippov
date: 2025-01-23
logsource:
  product: linux
  service: auth
detection:
  selection:
    process.name: useradd
  condition: selection
level: medium
tags:
  - attack.persistence
  - attack.t1136.001
falsepositives:
  - Legitimate user provisioning
  - System installation or automation scripts
