---
- name: Install AD-Domain-Services
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present

- name: Create Domain (Promote to DC)
  ansible.windows.win_domain:
    dns_domain_name: corp.local
    safe_mode_password: "Password123!" # Пароль для восстановления
  register: ad_promotion

- name: Reboot if promotion happened
  win_reboot:
  when: ad_promotion.reboot_required